import Head from 'next/head'
import Header from '../components/header/Header'

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Google Docs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
       <Header/>
          <section  className="bg-[#F8F9FA] pb-10 px-10">
            <div className="max-w-3xl mx-auto">
                <div className="py-6">
                  <h2>Start a new document</h2>
                </div>
            </div>
          </section>
    </div>
  )
}
