import Head from 'next/head'
import Header from '../components/header/Header'
import Button from "@material-tailwind/react/Button"
import Icon from "@material-tailwind/react/Icon"
import Image from "next/image"


export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Google Docs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
       <Header/>
          <section  className="bg-[#F8F9FA] pb-10 px-10">
            <div className="max-w-3xl mx-auto">
                <div className="py-6 flex items-center justify-between">
                  <h2 className="text-gray-700 text-lg">Start a new document</h2>

                  <Button
              color="gray"
              buttonType="outline"
              iconOnly={true}
              ripple="dark"
              className="border-0"
            
            >
                <Icon
                    size="3xl"
                    name="more_vert"
                />
                </Button>
                </div>

                <div>
                   <Image
                      src="https://links.papareact.com/pju"
                       layout="fill"
                   />
                </div>
            </div>
          </section>
    </div>
  )
}
